configs:
  mode:
    runner: "usb"
    sequentialSubtraction: false
  sensor:
    general:
      fpsBoost: true
      brightness:
        alpha: 1.0
        beta: 0.0
    usbCam:
      maskSize: 0.8
      flipImage: true
      enableMask: true
      ports:
        lCam: "/dev/video4"
        rCam: "/dev/video6"
  algorithm:
    process:
      alignment:
        matchRate: 0.4
        usePreset: true
        maxFeatures: 500
      channel: "g" # ["b", "g", "r", "all"]
      subtractRL: true
    postprocess:
      threshold:
        size: 50
        method: "binary" # ["binary", "otsu", "both"]
      invertBinary: false
      erosionKernelSize: 1
      gaussianKernelSize: 1
  marker:
    structure:
      size: 0.1
    detection:
      dictionary: "DICT_ARUCO_ORIGINAL"
