configs:
  gui:
    windowWidth: 1800
  sensor:
    exposureTime: 20000
    brightness:
      alpha: 5.0
      beta: 0.0
  markers:
    leftHanded: false
  preProcessing:
    fpsBoost: true
    channel: "g"
    roiDimension:
      cap1:
        x: 520
        y: 200
        width: 976
        height: 1094
      cap2:
        x: 480
        y: 212
        width: 976
        height: 1094
    homographyMat: "Settings2"
    sensorProjectConfigPath: "csr_sensors/sensors/config"
  processing:
    flipImage: true
    maxFeatures: 500
    preAligment: true
    invertBinaryImage: true
    goodMatchPercentage: 0.4
    enableCircularROI: false
    circlularMaskCoverage: 0.8
    isSequentialSubtraction: true
  postProcessing:
    threshold: 35
    erodeKernelSize: 5
    gaussianBlurKernelSize: 3
    thresholdMethod: "binary"
